"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
type Service={id:string;title:string;description:string;price:number;image:string|null};
const blank={title:"",description:"",price:""};
export default function OwnerServices(){
 const [services,setServices]=useState<Service[]>([]),[form,setForm]=useState(blank),[editing,setEditing]=useState<Service|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{const r=await fetch('/api/services',{cache:'no-store'}); if(r.ok)setServices(await r.json())}; useEffect(()=>{load()},[]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch('/api/services',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({title:form.title.trim(),description:form.description.trim(),price:Number(form.price),image:null})});const d=await r.json();if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);setForm(blank);setMessage('Service added. It is live on the Services page.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Could not add service.')}finally{setBusy(false)}};
 const save=async()=>{if(!editing)return;setBusy(true);setMessage("");try{const r=await fetch(`/api/services/${editing.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(editing)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save service');setEditing(null);setMessage('Changes saved.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Could not save service.')}finally{setBusy(false)}};
 const del=async(id:string)=>{if(!confirm('Delete this service?'))return;const r=await fetch(`/api/services/${id}`,{method:'DELETE',credentials:'same-origin'});if(r.ok){setMessage('Service deleted.');await load()}else setMessage('Could not delete service.')};
 const input='w-full rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-white outline-none focus:border-[#ef233c]';
 return <div className="min-h-screen bg-[#070707] text-white"><main className="mx-auto max-w-6xl px-6 py-12"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.3em] text-[#ef233c]">Owner tools</p><h1 className="mt-2 text-3xl font-black">Services</h1><p className="mt-2 text-sm text-neutral-400">Add a package here and it will show on the public Services page.</p></div><Link href="/owner/dashboard" className="rounded-full border border-white/10 px-5 py-2.5 text-sm font-semibold">Back</Link></div>
 {message&&<div className="mt-7 rounded-2xl border border-[#ef233c]/30 bg-[#ef233c]/10 p-4 text-sm">{message}</div>}
 <form onSubmit={create} className="mt-8 rounded-[1.75rem] border border-white/10 bg-[#101010] p-7"><h2 className="text-xl font-bold">Add a service</h2><div className="mt-5 grid gap-4"><input required className={input} placeholder="Package name" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea required rows={4} className={input} placeholder="What's included? Write it how you'd explain it to a customer." value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input required min="0" type="number" className={input} placeholder="Starting price" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><button disabled={busy} className="w-fit rounded-full bg-[#ef233c] px-6 py-3 font-bold hover:bg-[#c9182b] disabled:opacity-50">{busy?'Adding…':'Add service'}</button></div></form>
 <div className="mt-8 space-y-4">{services.length===0&&<div className="rounded-2xl border border-dashed border-white/15 p-8 text-center text-neutral-500">No custom services yet. Add your first one above.</div>}{services.map(s=><div key={s.id} className="rounded-[1.5rem] border border-white/10 bg-[#101010] p-6">{editing?.id===s.id?<div className="grid gap-4"><input className={input} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/><textarea rows={4} className={input} value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/><input type="number" className={input} value={editing.price} onChange={e=>setEditing({...editing,price:Number(e.target.value)})}/><div className="flex gap-3"><button onClick={save} disabled={busy} className="rounded-full bg-[#ef233c] px-5 py-2.5 text-sm font-bold">Save</button><button onClick={()=>setEditing(null)} className="rounded-full border border-white/10 px-5 py-2.5 text-sm">Cancel</button></div></div>:<div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-xl font-bold">{s.title}</h2><p className="mt-2 whitespace-pre-line text-sm leading-7 text-neutral-400">{s.description}</p><p className="mt-3 font-bold text-[#ef233c]">Starting at ${s.price}</p></div><div className="flex gap-2"><button onClick={()=>setEditing(s)} className="rounded-full border border-white/10 px-4 py-2 text-sm">Edit</button><button onClick={()=>del(s.id)} className="rounded-full border border-[#ef233c]/30 px-4 py-2 text-sm text-[#ff697a]">Delete</button></div></div>}</div>)}</div>
 </main></div>
}
