export const SITE_DEFAULTS = {
  heroEyebrow: "South Elgin • Mobile Detailing",
  heroTitle: "A cleaner car without making your day harder.",
  heroBody: "Interior, exterior, paint correction, and protection done with a clean process and no unnecessary runaround.",
  heroPrimaryCta: "Book a Detail",
  heroSecondaryCta: "See Services",
  introEyebrow: "Car Dash Detailing",
  introTitle: "Good detailing should feel simple from start to finish.",
  introBody: "Pick what the vehicle needs, send the details, and get a clear plan before the work starts. No overcomplicated packages or weird sales pitch.",
  storyEyebrow: "The Finish Matters",
  storyTitle: "The difference is usually in the parts people skip.",
  storyBody: "Glass, trim, tight interior areas, paint clarity, and the final wipe-down all matter. The goal is a vehicle that looks properly finished, not just recently washed.",
  servicesEyebrow: "Services",
  servicesTitle: "Start with the service that makes sense for the car.",
  servicesBody: "Packages and pricing stay current through the Owner Dashboard. Extra work is discussed before anything gets added.",
  galleryEyebrow: "Recent Work",
  galleryTitle: "A look at what has been coming through lately.",
  contactTitle: "Need the car taken care of?",
  contactBody: "Send the vehicle info and what it needs. Availability and the right service can be figured out from there.",
  footerBlurb: "Mobile detailing based in South Elgin, serving nearby areas with interior, exterior, paint-care, and protection services.",
  supportButtonLabel: "Support",
  supportTitle: "Need help with something?",
  supportIntro: "Send a quick message here. Keep the chat open for live replies, or leave an email or phone number for a later follow-up.",
} as const;

export type SiteContentKey = keyof typeof SITE_DEFAULTS;
