"use client";
import { useEffect, useState } from "react";

type Service = { id:string; title:string; description:string; price:number; startingPrice:number|null; maxPrice:number|null; pricingType:string; category:string; subcategory:string; active:boolean; sortOrder:number };
type Draft = Omit<Service,"id"|"price"|"startingPrice"|"maxPrice"|"sortOrder"> & { price:string; startingPrice:string; maxPrice:string; sortOrder:string };
const empty:Draft={title:"",description:"",price:"",startingPrice:"",maxPrice:"",pricingType:"fixed",category:"Car Detailing",subcategory:"Package Detailing",active:true,sortOrder:"0"};
const input="w-full rounded-2xl border border-white/10 bg-black/40 px-4 py-3 text-white outline-none focus:border-red-500/60";
export default function OwnerServices(){
 const [items,setItems]=useState<Service[]>([]),[draft,setDraft]=useState<Draft>(empty),[edit,setEdit]=useState<string|null>(null),[editDraft,setEditDraft]=useState<Draft>(empty),[message,setMessage]=useState("");
 const load=async()=>{const r=await fetch('/api/services',{cache:'no-store'}); if(r.ok)setItems(await r.json())}; useEffect(()=>{load()},[]);
 const payload=(d:Draft)=>({...d,price:Number(d.price||0),startingPrice:d.startingPrice===""?null:Number(d.startingPrice),maxPrice:d.maxPrice===""?null:Number(d.maxPrice),sortOrder:Number(d.sortOrder||0)});
 const create=async(e:React.FormEvent)=>{e.preventDefault();setMessage("");const r=await fetch('/api/services',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload(draft))});const x=await r.json();setMessage(r.ok?'Service added.':x.error||'Could not add service.');if(r.ok){setDraft(empty);load()}};
 const start=(s:Service)=>{setEdit(s.id);setEditDraft({...s,price:String(s.price||""),startingPrice:s.startingPrice==null?"":String(s.startingPrice),maxPrice:s.maxPrice==null?"":String(s.maxPrice),sortOrder:String(s.sortOrder),id:undefined} as unknown as Draft)};
 const save=async(id:string)=>{const r=await fetch(`/api/services/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload(editDraft))});setMessage(r.ok?'Service updated.':'Could not update service.');if(r.ok){setEdit(null);load()}};
 const del=async(id:string)=>{if(!confirm('Delete this service?'))return;await fetch(`/api/services/${id}`,{method:'DELETE'});load()};
 const form=(d:Draft,setD:(x:Draft)=>void)=><div className="grid gap-4 md:grid-cols-2">
   <label className="text-sm text-white/55">Service name<input className={`${input} mt-2`} value={d.title} onChange={e=>setD({...d,title:e.target.value})}/></label>
   <label className="text-sm text-white/55">Category<select className={`${input} mt-2`} value={d.category} onChange={e=>setD({...d,category:e.target.value})}><option>Car Detailing</option><option>Marine Detailing</option><option>Ceramic Coatings</option></select></label>
   <label className="text-sm text-white/55">Subcategory<input className={`${input} mt-2`} value={d.subcategory} onChange={e=>setD({...d,subcategory:e.target.value})} placeholder="Exterior / Interior / Buff and Polish"/></label>
   <label className="text-sm text-white/55">Pricing type<select className={`${input} mt-2`} value={d.pricingType} onChange={e=>setD({...d,pricingType:e.target.value})}><option value="fixed">Fixed price</option><option value="starting">Starting price</option><option value="range">Estimate range</option><option value="quote">Quote required</option></select></label>
   {d.pricingType==='fixed'&&<label className="text-sm text-white/55">Fixed price<input type="number" className={`${input} mt-2`} value={d.price} onChange={e=>setD({...d,price:e.target.value})}/></label>}
   {d.pricingType==='starting'&&<label className="text-sm text-white/55">Starting price<input type="number" className={`${input} mt-2`} value={d.startingPrice} onChange={e=>setD({...d,startingPrice:e.target.value})}/></label>}{d.pricingType==='range'&&<label className="text-sm text-white/55">Estimate minimum<input type="number" className={`${input} mt-2`} value={d.startingPrice} onChange={e=>setD({...d,startingPrice:e.target.value})}/><span className="mt-1 block text-xs text-white/30">Lowest normal estimate before vehicle/condition adjustments.</span></label>}
   {d.pricingType==='range'&&<label className="text-sm text-white/55">Estimate maximum<input type="number" className={`${input} mt-2`} value={d.maxPrice} onChange={e=>setD({...d,maxPrice:e.target.value})}/><span className="mt-1 block text-xs text-white/30">Normal high end shown before vehicle/condition adjustments.</span></label>}
   <label className="text-sm text-white/55">Menu order<input type="number" className={`${input} mt-2`} value={d.sortOrder} onChange={e=>setD({...d,sortOrder:e.target.value})}/></label>
   <label className="md:col-span-2 text-sm text-white/55">Description<textarea className={`${input} mt-2 min-h-28`} value={d.description} onChange={e=>setD({...d,description:e.target.value})}/></label>
   <label className="flex items-center gap-3 text-sm text-white/65"><input type="checkbox" checked={d.active} onChange={e=>setD({...d,active:e.target.checked})}/> Show on website</label>
 </div>;
 return <main className="min-h-screen bg-[#070707] text-white"><div className="mx-auto max-w-7xl px-6 py-10"><div className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.28em] text-red-400">Owner</p><h1 className="mt-2 text-4xl font-semibold">Services & pricing</h1><p className="mt-2 text-white/40">Build the Services dropdown and control fixed prices, starting prices, estimate minimum/maximum ranges, or quote-only pricing.</p></div><a href="/owner/dashboard" className="h-fit rounded-full border border-white/15 px-5 py-3 text-sm">Back</a></div>
 <form onSubmit={create} className="mt-8 rounded-[28px] border border-white/10 bg-white/[.03] p-6"><h2 className="mb-5 text-2xl font-semibold">Add service</h2>{form(draft,setDraft)}<button className="mt-6 rounded-full bg-red-600 px-6 py-3 font-semibold">Add service</button></form>
 {message&&<p className="mt-4 text-sm text-white/60">{message}</p>}
 <div className="mt-10 grid gap-5">{items.map(s=><article key={s.id} className="rounded-[28px] border border-white/10 bg-white/[.025] p-6">{edit===s.id?<>{form(editDraft,setEditDraft)}<div className="mt-5 flex gap-3"><button onClick={()=>save(s.id)} className="rounded-full bg-red-600 px-5 py-2.5">Save</button><button onClick={()=>setEdit(null)} className="rounded-full border border-white/15 px-5 py-2.5">Cancel</button></div></>:<div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs uppercase tracking-[.22em] text-red-400">{s.category} · {s.subcategory}</p><h3 className="mt-2 text-2xl font-semibold">{s.title}</h3><p className="mt-2 text-white/45">{s.description}</p><p className="mt-3 font-semibold">{s.pricingType==='fixed'?`$${s.price}`:s.pricingType==='starting'?`Starting at $${s.startingPrice}`:s.pricingType==='range'?`Usually $${s.startingPrice}–$${s.maxPrice}`:'Quote required'} {!s.active&&<span className="ml-2 text-white/30">· hidden</span>}</p></div><div className="flex gap-2"><button onClick={()=>start(s)} className="rounded-full border border-white/15 px-4 py-2 text-sm">Edit</button><button onClick={()=>del(s.id)} className="rounded-full border border-red-500/30 px-4 py-2 text-sm text-red-300">Delete</button></div></div>}</article>)}</div>
 </div></main>
}
