"use client";
import { useEffect, useState } from "react";
import { DEFAULT_BOOKING_PRICING, parseBookingPricingConfig } from "@/lib/booking-pricing";
import { DEFAULT_PRICING_PAGES, parsePricingConfig } from "@/lib/pricing-config";
import { DEFAULT_PROMOTIONS, type PromotionSettings, type Promotion } from "@/lib/promotions";
const field="w-full rounded-xl border border-white/15 bg-black/40 p-3 text-white";
const blank=():Promotion=>({id:"sale-"+Date.now(),title:"New promotion",enabled:false,scope:"all",target:"",type:"percent",amount:25,startsAt:"",endsAt:""});
export default function PromotionsPage(){
  const [settings,setSettings]=useState<PromotionSettings>(DEFAULT_PROMOTIONS);
  const [message,setMessage]=useState("");
  const [saving,setSaving]=useState(false);
  const [targets,setTargets]=useState<{category:string;packages:string;services:string;addon:string}[]>([]);
  useEffect(()=>{Promise.all([fetch("/api/site-content",{cache:"no-store"}).then(r=>r.json()),fetch("/api/services",{cache:"no-store"}).then(r=>r.json())]).then(([content,services])=>{
    const options:{category:string;packages:string;services:string;addon:string}[]=[];
    for(const kind of ["packages","interior","exterior"] as const){
      const config=parsePricingConfig(content?.[kind==="packages"?"pricingPackagesConfig":kind==="interior"?"pricingInteriorConfig":"pricingExteriorConfig"],DEFAULT_PRICING_PAGES[kind]);
      for(const item of config.packages)options.push({category:kind,packages:kind+":"+item.id,services:item.name,addon:""});
    }
    for(const item of (Array.isArray(services)?services:[]))options.push({category:"service",packages:"",services:item.title,addon:"service:"+item.id});
    const pricing=parseBookingPricingConfig(content?.bookingPricingConfig);
    for(const item of pricing.addOns||DEFAULT_BOOKING_PRICING.addOns)options.push({category:"addon",packages:"",services:item.name,addon:"addon:"+item.id});
    setTargets(options);
  }).catch(()=>{});},[]);
  useEffect(()=>{fetch("/api/promotions",{cache:"no-store"}).then(r=>r.json()).then(setSettings).catch(()=>setMessage("Unable to load promotions."));},[]);
  function edit(index:number,next:Promotion){setSettings(s=>({...s,promotions:s.promotions.map((p,i)=>i===index?next:p)}));}
  async function save(){setSaving(true);setMessage("");try{const r=await fetch("/api/promotions",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(settings)});const json=await r.json();if(!r.ok)throw new Error(json.error||"Save failed");setSettings(json);setMessage("Promotion settings saved. Public discounts remain staged until checkout integration is verified.");}catch(e){setMessage(e instanceof Error?e.message:"Save failed");}finally{setSaving(false);}}
  return <main className="min-h-screen bg-[#080808] p-5 text-white md:p-10"><div className="mx-auto max-w-5xl">
  <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs uppercase tracking-[.22em] text-[#6EAEC6]">Owner dashboard</p><h1 className="mt-2 text-4xl font-semibold">Promotions Manager</h1><p className="mt-2 text-white/50">Build targeted sales and seasonal announcements without changing your standard pricing.</p></div><a className="rounded-full border border-white/20 px-5 py-3" href="/owner/dashboard">Dashboard</a></div>
  <section className="mt-8 rounded-3xl border border-white/10 bg-white/[.04] p-6"><h2 className="text-2xl font-semibold">Announcement banner</h2><p className="mt-2 text-sm text-white/50">An independent banner that can be enabled or hidden.</p><label className="mt-4 flex gap-3"><input type="checkbox" checked={settings.bannerEnabled} onChange={e=>setSettings({...settings,bannerEnabled:e.target.checked})}/>Enable banner</label>
  <div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm">Custom text<input className={field+" mt-2"} maxLength={120} value={settings.bannerText} placeholder="25% OFF SPRING DETAILING" onChange={e=>setSettings({...settings,bannerText:e.target.value})}/></label><label className="text-sm">Click destination<input className={field+" mt-2"} value={settings.bannerLink} placeholder="/#prices" onChange={e=>setSettings({...settings,bannerLink:e.target.value})}/></label></div>
  <div className="mt-5 rounded-xl bg-[#9f2424] p-4 text-center text-sm font-bold uppercase tracking-widest">{settings.bannerText||"YOUR SALE ANNOUNCEMENT"}</div></section>
  <section className="mt-7 rounded-3xl border border-white/10 bg-white/[.04] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-semibold">Discount rules</h2><p className="mt-2 text-sm text-white/50">Percentage or dollar-off. Exactly one discount rule per item; no stacking.</p></div><button className="rounded-full bg-[#6EAEC6] px-5 py-3 font-semibold text-[#0B1822]" onClick={()=>setSettings(s=>({...s,promotions:[...s.promotions,blank()]}))}>+ Add promotion</button></div>
  <div className="mt-5 space-y-4">{settings.promotions.map((p,i)=><article key={p.id} className="rounded-2xl border border-white/10 p-4"><div className="mb-4 flex items-center justify-between"><label className="flex gap-2"><input type="checkbox" checked={p.enabled} onChange={e=>edit(i,{...p,enabled:e.target.checked})}/>Enabled</label><button className="text-red-300" onClick={()=>setSettings(s=>({...s,promotions:s.promotions.filter(x=>x.id!==p.id)}))}>Remove</button></div>
  <div className="grid gap-4 md:grid-cols-3"><label className="text-sm">Campaign<input className={field+" mt-2"} value={p.title} onChange={e=>edit(i,{...p,title:e.target.value})}/></label><label className="text-sm">Applies to<select className={field+" mt-2"} value={p.scope} onChange={e=>edit(i,{...p,scope:e.target.value as Promotion["scope"],target:""})}>{["all","category","package","service","addon"].map(x=><option key={x} value={x}>{x==="all"?"Entire menu":x}</option>)}</select></label><label className="text-sm">Target<select className={field+" mt-2"} value={p.target} disabled={p.scope==="all"} onChange={e=>edit(i,{...p,target:e.target.value})}><option value="">Select a target</option>{p.scope==="category" && ["packages","interior","exterior"].map(x=><option key={x} value={x}>{x}</option>)}{p.scope==="package" && targets.filter(x=>x.packages).map(x=><option key={x.packages} value={x.packages}>{x.category} / {x.services}</option>)}{p.scope==="service" && targets.filter(x=>x.category==="service").map(x=><option key={x.addon} value={x.addon}>{x.services}</option>)}{p.scope==="addon" && targets.filter(x=>x.category==="addon").map(x=><option key={x.addon} value={x.addon}>{x.services}</option>)}</select></label><label className="text-sm">Discount type<select className={field+" mt-2"} value={p.type} onChange={e=>edit(i,{...p,type:e.target.value as Promotion["type"]})}><option value="percent">Percentage off</option><option value="fixed">Dollar amount off</option></select></label><label className="text-sm">Discount amount<input className={field+" mt-2"} type="number" min="0.01" max={p.type==="percent"?100:undefined} step="0.01" value={p.amount} onChange={e=>edit(i,{...p,amount:Number(e.target.value)})}/></label><div className="text-sm">Example<div className="mt-2 rounded-xl border border-white/10 p-3"><span className="mr-2 text-white/40 line-through">$249.00</span><strong className="text-red-400">${Math.max(0,249-(p.type==="percent"?249*p.amount/100:p.amount)).toFixed(2)}</strong></div></div><label className="text-sm">Starts (optional)<input type="date" className={field+" mt-2"} value={p.startsAt} onChange={e=>edit(i,{...p,startsAt:e.target.value})}/></label><label className="text-sm">Ends (optional)<input type="date" className={field+" mt-2"} value={p.endsAt} onChange={e=>edit(i,{...p,endsAt:e.target.value})}/></label></div></article>)}</div></section>
  <div className="mt-6 flex flex-wrap items-center gap-4"><button disabled={saving} onClick={save} className="rounded-full bg-[#6EAEC6] px-7 py-3 font-semibold text-[#0B1822] disabled:opacity-50">{saving?"Saving...":"Save promotions"}</button><p role="status" className="text-sm text-white/60">{message}</p></div>
  </div></main>;
}
